"use client";

import { Canvas, useFrame } from "@react-three/fiber";
import { PerspectiveCamera } from "@react-three/drei";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { useGameStore } from "@/lib/store";
import { COLLISION_Z, LANES, MAX_SPEED, PLAYER_Z, START_SPEED, laneX } from "@/lib/game";
import type { Entity, Orb, Powerup, PowerupKind } from "@/lib/game";

const colors = { cyan: "#68f7ff", pink: "#ff3eaa", lime: "#d7ff62", purple: "#673cff" };

function Player() {
  const group = useRef<THREE.Group>(null);
  const lane = useGameStore((state) => state.lane);
  const jumping = useGameStore((state) => state.jumping);
  const sliding = useGameStore((state) => state.sliding);
  useFrame(({ clock }, delta) => { if (!group.current) return; group.current.position.x = THREE.MathUtils.damp(group.current.position.x, laneX(lane), 10, delta); group.current.position.y = 0.8 + (jumping ? .7 : 0) + Math.sin(clock.elapsedTime * 5) * 0.08; group.current.rotation.z = THREE.MathUtils.damp(group.current.rotation.z, -lane * 0.12, 8, delta); });
  return <group ref={group} position={[0, .8, PLAYER_Z]}><mesh rotation={[0, 0, -.05]}><boxGeometry args={[1.8, .18, .75]} /><meshStandardMaterial color={colors.pink} emissive={colors.pink} emissiveIntensity={4} /></mesh><mesh position={[0, sliding ? .12 : .3, 0]} scale={sliding ? [1.2, .65, 1] : [1, 1, 1]}><capsuleGeometry args={[.23, .7, 4, 8]} /><meshStandardMaterial color="#d8e7ff" emissive={colors.cyan} emissiveIntensity={.8} /></mesh><mesh position={[0, sliding ? .45 : .82, 0]}><sphereGeometry args={[.22, 12, 8]} /><meshStandardMaterial color="#11182c" emissive={colors.cyan} emissiveIntensity={1.5} /></mesh><pointLight color={colors.cyan} intensity={3} distance={5} /></group>;
}

function World({ entities, orbs, powerups }: { entities: Entity[]; orbs: Orb[]; powerups: Powerup[] }) {
  return <><mesh position={[0, -.25, -65]}><boxGeometry args={[11, .5, 150]} /><meshStandardMaterial color="#11152a" metalness={.5} roughness={.7} /></mesh>{LANES.map((lane) => <mesh key={lane} position={[laneX(lane), .01, -65]}><boxGeometry args={[.025, .025, 150]} /><meshStandardMaterial color={colors.cyan} emissive={colors.cyan} emissiveIntensity={5} /></mesh>)}{Array.from({ length: 22 }, (_, index) => { const side = index % 2 ? 1 : -1; const x = side * (7 + (index % 4) * 2); const z = -index * 7 - 5; const height = 3 + (index % 5) * 1.5; return <mesh key={`building-${index}`} position={[x, height / 2 - .2, z]}><boxGeometry args={[2.5 + index % 3, height, 5]} /><meshStandardMaterial color="#101731" emissive={index % 2 ? colors.purple : colors.pink} emissiveIntensity={.4} /></mesh>; })}{entities.map((entity) => <mesh key={entity.id} position={[laneX(entity.lane), entity.kind === "gate" ? 1.2 : entity.kind === "drone" ? 1.8 : .7, entity.z]} rotation={entity.kind === "drone" ? [0, 0, .4] : [0, 0, 0]}><boxGeometry args={entity.kind === "gate" ? [1.9, .35, 1] : entity.kind === "drone" ? [1.2, .7, 1.2] : [1.9, 1.4, 1]} /><meshStandardMaterial color={entity.kind === "gate" ? colors.lime : colors.pink} emissive={entity.kind === "gate" ? colors.lime : colors.pink} emissiveIntensity={3} /></mesh>)}{orbs.map((orb) => <mesh key={orb.id} position={[laneX(orb.lane), orb.y, orb.z]} rotation={[0, 0, Math.PI / 4]}><octahedronGeometry args={[.28, 0]} /><meshStandardMaterial color={colors.cyan} emissive={colors.cyan} emissiveIntensity={5} /></mesh>)}{powerups.map((powerup) => <mesh key={powerup.id} position={[laneX(powerup.lane), 1, powerup.z]}><icosahedronGeometry args={[.42, 1]} /><meshStandardMaterial color={powerup.kind === "shield" ? colors.cyan : powerup.kind === "boost" ? colors.lime : colors.pink} emissive={powerup.kind === "shield" ? colors.cyan : powerup.kind === "boost" ? colors.lime : colors.pink} emissiveIntensity={4} /></mesh>)}</>;
}

function RunnerScene() {
  const [entities, setEntities] = useState<Entity[]>([]); const [orbs, setOrbs] = useState<Orb[]>([]); const [powerups, setPowerups] = useState<Powerup[]>([]); const nextId = useRef(1); const spawnTimer = useRef(0);
  const status = useGameStore((state) => state.status); const store = useGameStore;
  const jumping = useGameStore((state) => state.jumping); const sliding = useGameStore((state) => state.sliding);
  useEffect(() => { if (!jumping && !sliding) return; const timer = window.setTimeout(() => useGameStore.setState({ jumping: false, sliding: false }), jumping ? 650 : 700); return () => window.clearTimeout(timer); }, [jumping, sliding]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (["ArrowLeft", "a", "ArrowRight", "d", "ArrowUp", " ", "ArrowDown", "Shift"].includes(event.key)) event.preventDefault(); if (["ArrowLeft", "a", "ArrowRight", "d"].includes(event.key)) store.getState().moveLane(event.key === "ArrowLeft" || event.key === "a" ? -1 : 1); if (["ArrowUp", " "].includes(event.key)) store.getState().jump(); if (["ArrowDown", "Shift"].includes(event.key)) store.getState().slide(); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [store]);
  useEffect(() => { let startX = 0; let startY = 0; const down = (event: TouchEvent) => { startX = event.touches[0].clientX; startY = event.touches[0].clientY; }; const up = (event: TouchEvent) => { const dx = event.changedTouches[0].clientX - startX; const dy = event.changedTouches[0].clientY - startY; if (Math.max(Math.abs(dx), Math.abs(dy)) < 30) return; if (Math.abs(dx) > Math.abs(dy)) store.getState().moveLane(dx > 0 ? 1 : -1); else if (dy < 0) store.getState().jump(); else store.getState().slide(); }; window.addEventListener("touchstart", down, { passive: true }); window.addEventListener("touchend", up, { passive: true }); return () => { window.removeEventListener("touchstart", down); window.removeEventListener("touchend", up); }; }, [store]);
  useFrame((state, delta) => { if (status !== "playing") return; const current = store.getState(); const speed = Math.min(MAX_SPEED, START_SPEED + current.distance * .012) * (current.boost ? 1.35 : 1); store.getState().tick(delta, speed); spawnTimer.current += delta; if (spawnTimer.current > Math.max(.55, 1.2 - current.distance / 800)) { spawnTimer.current = 0; const lane = LANES[Math.floor(Math.random() * 3)]; const id = nextId.current++; setEntities((items) => [...items, { id, lane, z: -85, kind: ["barrier", "gate", "drone"][Math.floor(Math.random() * 3)] as Entity["kind"] }]); if (Math.random() > .25) setOrbs((items) => [...items, { id: nextId.current++, lane: LANES[Math.floor(Math.random() * 3)], z: -85 - 3, y: 1 + Math.random() * .8 }]); if (Math.random() > .92) setPowerups((items) => [...items, { id: nextId.current++, lane, z: -90, kind: ["shield", "magnet", "boost"][Math.floor(Math.random() * 3)] as PowerupKind }]); } const move = speed * delta; setEntities((items) => items.map((item) => ({ ...item, z: item.z + move })).filter((item) => { if (item.z > 6) return false; if (Math.abs(item.z - PLAYER_Z) < COLLISION_Z && item.lane === current.lane) { const safe = (item.kind === "barrier" && current.distance % 2 < .35) || (item.kind === "gate" && current.distance % 2 > .35); if (!safe) store.getState().hit(); } return true; })); setOrbs((items) => items.map((orb) => ({ ...orb, z: orb.z + move })).filter((orb) => { if (orb.z > 6) return false; if (Math.abs(orb.z - PLAYER_Z) < 1.1 && orb.lane === current.lane) { store.getState().collectOrb(); return false; } return true; })); setPowerups((items) => items.map((powerup) => ({ ...powerup, z: powerup.z + move })).filter((powerup) => { if (powerup.z > 6) return false; if (Math.abs(powerup.z - PLAYER_Z) < 1.1 && powerup.lane === current.lane) { store.getState().collectPowerup(powerup.kind); return false; } return true; })); state.camera.position.x = THREE.MathUtils.damp(state.camera.position.x, laneX(current.lane) * .16, 3, delta); state.camera.position.y = THREE.MathUtils.damp(state.camera.position.y, 4.7, 3, delta); state.camera.lookAt(0, .7, -12); });
  return <><PerspectiveCamera makeDefault position={[0, 4.7, 10]} fov={62} /><ambientLight intensity={.45} color="#8d9cff" /><directionalLight position={[4, 8, 4]} intensity={1.3} color="#b8d8ff" /><fog attach="fog" args={["#080b1b", 18, 105]} /><Player /><World entities={entities} orbs={orbs} powerups={powerups} /></>;
}

export default function GameCanvas() { return <div className="game-canvas"><Canvas dpr={[1, 1.5]} gl={{ antialias: false }}><RunnerScene /></Canvas></div>; }
